{% set version = "2.10.1" %}
{% set sha256 = "110729decf082f69b90b058c0cabaea38f771983a564308ae19cb30a68ce7b86" %}

package:
  name: blast
  version: {{ version }}

source:
  url: https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/{{ version }}/ncbi-blast-{{ version }}+-src.tar.gz
  sha256: {{ sha256 }}

build:
  number: 4

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - zlib
    - bzip2
    - pcre
    - entrez-direct
    - curl
  run:
    - zlib
    - bzip2
    - pcre
    - perl
    - perl-list-moreutils
    - perl-archive-tar
    - perl-json
    - entrez-direct
    - curl

test:
  files:
    - test.fa
    - testdatabase.fa
  commands:
    # (see run_test.sh for remainder of tests)
    - blastn -help
    - blastp -help
    - makeblastdb -help
    - blastdb_aliastool -version > /dev/null
    - blastdbcheck -version > /dev/null
    - blastdbcmd -version > /dev/null
    - blastn -version > /dev/null
    - blastp -version > /dev/null
    - blastx -version > /dev/null
    - convert2blastmask -version > /dev/null
    - dustmasker -version > /dev/null
    - makeblastdb -version > /dev/null
    - makembindex -version > /dev/null
    - psiblast -version > /dev/null
    - rpsblast -version > /dev/null
    - rpstblastn -version > /dev/null
    - segmasker -version > /dev/null
    - tblastn -version > /dev/null
    - tblastx -version > /dev/null
    - windowmasker -version > /dev/null
    - update_blastdb.pl --version > /dev/null
    - get_species_taxids.sh -h > /dev/null

about:
  home: http://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE_TYPE=BlastDocs
  license: Public Domain
  summary: BLAST+ is a new suite of BLAST tools that utilizes the NCBI C++ Toolkit.

extra:
  identifiers:
    - biotools:blast
    - doi:10.1016/S0022-2836(05)80360-2
  recipe-maintainers:
    - christiam
    - epruesse
    - veraalva
