package:
  name: discosnp
  version: '2.5.4'

source:
  url: "https://github.com/GATB/DiscoSnp/releases/download/v2.5.4/DiscoSNP.-v2.5.4-bin-Linux.tar.gz"
  sha256: "2ecbdc585460f43fe85ebf0d1719a6363070651c5bbb4b733500ec3556a0791c"

build:
  number: 0
  # requires clang>=4.5
  skip: True  # [osx]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
  host:
    - zlib
  run:
    - zlib
    - bwa
    - shortreadconnector
    - python >=3.0

test:
  commands:
    - run_discoSnp++.sh -h
    - run_discoSnpRad.sh -h

about:
  home: https://gatb.inria.fr/software/discosnp/
  license: GNU Affero General Public License v3.0
  summary: reference-free small variant caller for short read sequencing data

extra:
  identifiers:
    - biotools:discosnp
    - doi:10.1093/nar/gkn000
