{% set version = "0.2.1" %}

package:
  name: starfish
  version: {{ version }}

source:
  url: https://github.com/spacetx/starfish/archive/{{ version }}.tar.gz
  sha256: 6026c689bcea5bbde2581f67fe70f889215f13e50ed7d2f8c22dc246f477f60b

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - click
    - dataclasses
    - h5py
    - jsonschema
    - matplotlib-base
    - numpy !=1.13.0
    - pandas >=0.23.4
    - regional
    - semantic_version
    - scikit-image >=0.14.0,!=0.16.0.*,!= 0.16.1.*,!=0.16.2.*
    - scikit-learn
    - scipy
    - showit >=1.1.4
    - slicedimage ==4.1.1
    - sympy
    - tqdm
    - trackpy
    - validators
    - xarray >=0.14.1
    - ipywidgets

test:
  imports:
    - starfish

about:
  home: https://github.com/spacetx/starfish
  license: MIT
  summary: standardized analysis pipeline for image-based transcriptomics
