package:
  name: admixtools
  version: '7.0'

source:
  url: https://github.com/DReichLab/AdmixTools/archive/v7.0.tar.gz
  sha256: 7fd77f6885e43ffc479a69034c9514983c557b67997ff0f94b6b1e9902c47f7c
  patches:
    - patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - gsl
    - openblas
  run:
    - gsl
    - openblas

about:
  home: https://github.com/DReichLab/AdmixTools
  license: Free for Academic Use
  summary: 'ADMIXTOOLS (Patterson et al. 2012) is a software package that supports formal tests of whether admixture occurred, and makes it possible to infer admixture proportions and dates.'

test:
  commands:
    - qp3Pop 2>&1 | grep Usage

extra:
  identifiers:
    - biotools:AdmixTools
    - doi:10.1534/genetics.112.145037
